# Generated by Django 6.0.7 on 2026-07-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('website_title', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='core/')),
                ('copyright', models.TextField(blank=True)),
            ],
        ),
    ]
