# Generated by Django 6.0.7 on 2026-07-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='core/'),
        ),
    ]
