# Generated by Django 6.0.7 on 2026-07-22 20:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_core_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='copyright',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
